# Generated by Django 4.2.16 on 2024-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.CharField(default='tester', max_length=100),
            preserve_default=False,
        ),
    ]
